#!/bin/bash
set -e

ZSH=~/.oh-my-zsh

if [[ ! -d $ZSH ]]
then
    if ! which git 2>/dev/null; then
        wget https://github.com/robbyrussell/oh-my-zsh/archive/master.zip
        unzip -oq master.zip
        rm -f master.zip
        mv oh-my-zsh-master $ZSH
    else
        git clone https://github.com/robbyrussell/oh-my-zsh.git $ZSH
    fi
else
    echo "oh-my-zsh already installed!"
fi

wget https://github.com/Janfy/dotfiles/archive/master.zip
unzip -q -j -o master.zip && rm -f master.zip
chsh -s $(which zsh)

# vi: ts=4 sw=4 filetype=sh
